# Generated by Django 5.0.6 on 2024-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("member_email", models.EmailField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=50, unique=True)),
                ("member_password", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("daily_accom", models.FloatField(default=0.0)),
            ],
        ),
    ]
