# Generated by Django 5.0.6 on 2024-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_custom_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_login',
        ),
        migrations.AddField(
            model_name='member',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='EmailAddress',
        ),
    ]
