# Generated by Django 5.0.6 on 2024-06-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_last_login_member_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_password',
        ),
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
