# Generated by Django 5.0.6 on 2024-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_member_password_member_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='member',
            name='member_password',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
