# Generated by Django 5.0.6 on 2024-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_use_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='member',
            name='account',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
