# Generated by Django 5.0.6 on 2024-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_options_member_member_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_password',
        ),
        migrations.AlterField(
            model_name='member',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
